# Generated by Django 3.1.7 on 2021-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210413_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='Post')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=350)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('date',), 'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
    ]
