# Generated by Django 3.1.7 on 2021-04-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210415_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date',), 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
