# Generated by Django 3.1.7 on 2021-04-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210415_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('date',), 'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
    ]
